# CMPSC 448: Homewrok #1
# Exploratory Data Analysis with `pandas`

## Objectives

In this assignment, you are asked to analyze the UCI Adult data set containing demographic information about the US residents. This data was extracted from the census bureau database found at

http://www.census.gov/ftp/pub/DES/www/welcome.html

The features of data with possible values of each feature are listed below:

| Feature Name| Possible Values  |
|------|------|
| age | continuous|
| workclass| Private, Self-emp-not-inc, Self-emp-inc, Federal-gov, Local-gov, State-gov, Without-pay, Never-worked|
| fnlwgt| continuous|
| education | Bachelors, Some-college, 11th, HS-grad, Prof-school, Assoc-acdm, Assoc-voc, 9th, 7th-8th, 12th, Masters, 1st-4th, 10th, Doctorate, 5th-6th, Preschool|
|education_num | continuous|
|marital_status | Married-civ-spouse, Divorced, Never-married, Separated, Widowed, Married-spouse-absent, Married-AF-spouse|
|occupation | Tech-support, Craft-repair, Other-service, Sales, Exec-managerial, Prof-specialty, Handlers-cleaners, Machine-op-inspct, Adm-clerical, Farming-fishing, Transport-moving, Priv-house-serv, Protective-serv, Armed-Forces|
|relationship | Wife, Own-child, Husband, Not-in-family, Other-relative, Unmarried |
|race | White, Asian-Pac-Islander, Amer-Indian-Eskimo, Other, Black|
|sex | Female, Male|
|capital_gain| continuous|
|capital_loss | continuous|
|hours-per-week | continuous |
|native-country | United-States, Cambodia, England, Puerto-Rico, Canada, Germany, Outlying-US(Guam-USVI-etc), India, Japan, Greece, South, China, Cuba, Iran, Honduras, Philippines, Italy, Poland, Jamaica, Vietnam, Mexico, Portugal, Ireland, France, Dominican-Republic, Laos, Ecuador, Taiwan, Haiti, Columbia, Hungary, Guatemala, Nicaragua, Scotland, Thailand, Yugoslavia, El-Salvador, Trinadad&Tobago, Peru, Hong, Holand-Netherlands |
|salary | >50K,<=50K |


Please  complete the tasks in the Jupyter notebook by answering following 8 questions.

In [3]:
import numpy as np
import pandas as pd
pd.set_option('display.max.columns', 100)
# to draw pictures in jupyter notebook
%matplotlib inline 
import matplotlib.pyplot as plt
import seaborn as sns
# we don't like warnings
# you can comment the following 2 lines if you'd like to
import warnings
warnings.filterwarnings('ignore')

In [30]:
data = pd.read_csv('adult.data.csv')
print("\n".join(data.columns))

age
 workclass
 fnlwgt
 education
 education-num
 marital-status
 occupation
 relationship
 race
 sex
 capital-gain
 capital-loss
 hours-per-week
 native-country
 salary

In [5]:
data.shape

(32561, 15)

In [37]:
data.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [20]:
# print(data.columns)

Index(['age', ' workclass', ' fnlwgt', ' education', ' education-num',
       ' marital-status', ' occupation', ' relationship', ' race', ' sex',
       ' capital-gain', ' capital-loss', ' hours-per-week', ' native-country',
       ' salary'],
      dtype='object')

In [32]:
# unique_country_values = data[" education"].unique()
# print(unique_country_values)

[' Bachelors' ' HS-grad' ' 11th' ' Masters' ' 9th' ' Some-college'
 ' Assoc-acdm' ' Assoc-voc' ' 7th-8th' ' Doctorate' ' Prof-school'
 ' 5th-6th' ' 10th' ' 1st-4th' ' Preschool' ' 12th']

### 1. How many men and women (sex feature) are represented in this dataset?

In [50]:
# You answer (code + results)

# Count the occurrences of each unique value in the "sex" column
sex_counts = data[" sex"].value_counts().reset_index()
sex_counts.columns = ["Sex", "Count"]
print(sex_counts)

       Sex  Count
0     Male  21790
1   Female  10771

### 2. What is the average age (age feature) of women?

In [73]:
# You answer (code + results)

# Filter the DataFrame to include only rows where "sex" is "female"
female = data[data[" sex"] == " Female"]

# Select the "age" column for the filtered rows
female_ages = female["age"]

# find average
average_age_women = female_ages.mean()

print(f"The average age of women is {average_age_women:}")

The average age of women is 36.85823043357163

### 3. What is the percentage of German citizens (native-country feature)?

In [11]:
# You answer (code + results)

# Filter rows where "native-country" is "Germany"
german_count = len(data[data[" native-country"] == " Germany"])

# find percentage of germans within the whole data set
german_percentage = (german_count / len(data)) * 100

print(f"The percentage of German citizens is {german_percentage:.2f}%")

The percentage of German citizens is 0.42%

###  4. What are the mean and standard deviation of age for those who earn more than 50K per year (salary feature) and those who earn less than 50K per year?

In [65]:
# You answer (code + results)

# mean and standard deviation of age for salary > 50K
mean_above_50 = data[data[" salary"] == " >50K"]["age"].mean()
std_above_50 = data[data[" salary"] == " >50K"]["age"].std()

# mean and standard deviation of age for salary  <=50K
mean_below_50 = data[data[" salary"] == " <=50K"]["age"].mean()
std_below_50 = data[data[" salary"] == " <=50K"]["age"].std()

print(f"Mean age for those who earn more than 50K per year: {mean_above_50:.2f}")
print(f"Standard deviation for those who earn more than 50K per year: {std_above_50:.2f}")
print()
print(f"Mean age for those who earn 50K or less per year: {mean_below_50:.2f}")
print(f"Standard deviationfor those who earn 50K or less per year: {std_below_50:.2f}")

Mean age for those who earn more than 50K per year: 44.25
Standard deviation for those who earn more than 50K per year: 10.52

Mean age for those who earn 50K or less per year: 36.78
Standard deviationfor those who earn 50K or less per year: 14.02

### 5. Is it true that people who earn more than 50K have at least high school education? (education – Bachelors, Prof-school, Assoc-acdm, Assoc-voc, Masters or Doctorate feature)

In [64]:
# You answer (code + results)

# those who earn above 50k
above_50_earners = data[data[" salary"] == " >50K"]

# education at least high school
edu_lvl = [" Bachelors", " Prof-school", " Assoc-acdm", " Assoc-voc", " Masters", " Doctorate"]

# the number of earners above 50K have that have at least a HS education
above_50_with_education = above_50_earners[above_50_earners[" education"].isin(edu_lvl)]

pct_above_50_with_education = (len(above_50_with_education) / len(above_50_earners)) * 100 

if pct_above_50_with_education == 100:
    print("True\n")
else:
    print("False\n")

print(f"No, not everyone who earns more than 50k has at least a HS education. The percentage of people who do is: {pct_above_50_with_education:.2f}%")

False

No, not everyone who earns more than 50k has at least a HS education. The percentage of people who do is: 57.84%

### 6.  Display age statistics for each race (race feature) and each gender (sex feature).

Hint: Use `groupby()` and `describe()` functions of DataFrame. Find the maximum age of men of Amer-Indian-Eskimo race.

In [13]:
# You answer (code + results)

# age statistics for each race and gender
age_statistics = data.groupby([" race", " sex"])["age"].describe()

Amer_Indian_Eskimo = age_statistics.loc[" Amer-Indian-Eskimo"]
Amer_Indian_Eskimo_Male = Amer_Indian_Eskimo.loc[" Male"]
Amer_Indian_Eskimo_Male_Max = Amer_Indian_Eskimo_Male.loc["max"]

print(age_statistics)
print()
print(f"The maximum age of men in Amer-Indian-Eskimo race is: {Amer_Indian_Eskimo_Male_Max}")

                             count       mean        std   min   25%   50%  \
 race               sex
Amer-Indian-Eskimo Female    119.0  37.117647  13.114991  17.0  27.0  36.0
                   Male      192.0  37.208333  12.049563  17.0  28.0  35.0
Asian-Pac-Islander Female    346.0  35.089595  12.300845  17.0  25.0  33.0
                   Male      693.0  39.073593  12.883944  18.0  29.0  37.0
Black              Female   1555.0  37.854019  12.637197  17.0  28.0  37.0
                   Male     1569.0  37.682600  12.882612  17.0  27.0  36.0
Other              Female    109.0  31.678899  11.631599  17.0  23.0  29.0
                   Male      162.0  34.654321  11.355531  17.0  26.0  32.0
White              Female   8642.0  36.811618  14.329093  17.0  25.0  35.0
                   Male    19174.0  39.652498  13.436029  17.0  29.0  38.0

                             75%   max
 race               sex
Amer-Indian-Eskimo Female  46.00  80.0
                   Male    45.00  82.0
Asian-Pac-Islander Female  43.75  75.0
                   Male    46.00  90.0
Black              Female  46.00  90.0
                   Male    46.00  90.0
Other              Female  39.00  74.0
                   Male    42.00  77.0
White              Female  46.00  90.0
                   Male    49.00  90.0

The maximum age of men in Amer-Indian-Eskimo race is: 82.0

### 7. What is the maximum number of hours a person works per week (hours-per-week feature)? How many people work such a number of hours, and what is the percentage of those who earn a lot (>50K) among them?

In [53]:
# You answer (code + results)
# 1.
# the maximum hours worked per week
max_hours = data[" hours-per-week"].max()
print(f"The maximum hours worked per week: {max_hours}\n")

# 2.
# how many people work that maximum number of hours
num_ppl_max_hrs = len(data[data[" hours-per-week"] == max_hours])
print(f"The number of people working the maximum hours per week: {num_ppl_max_hrs}\n")

# 3. % of max hour workers that make 50 or more
max_hour_workers = data[data[" hours-per-week"] == max_hours]
# count of how many people make over 50k
above_50_earners = max_hour_workers[max_hour_workers[" salary"] == " >50K"]
num_high_earners = len(above_50_earners)

# percent of people who work the max hours and make over 50k
percentage_above_50_earners = (num_high_earners / num_ppl_max_hrs) * 100

print(f"The percent of people who make more than 50k and work max hours is: {percentage_above_50_earners:.2f}%")

The maximum hours worked per week: 99

The number of people working the maximum hours per week: 85

The percent of people who make more than 50k and work max hours is: 29.41%

### 8. Count the average time of work (hours-per-week) for those who earn a little and a lot (salary) for each country (native-country). What will these be for Japan?

In [72]:
# You answer (code + results)

# average hours per work week grouping by salary and country
avg_hours = data.groupby([" salary", " native-country"])[" hours-per-week"].mean().reset_index()
print(avg_hours)

# filter out results to include only japan above and below 50
japan_avg_hours = avg_hours[avg_hours[" native-country"] == " Japan"]
japan_avg_hours

    salary    native-country  hours-per-week
0    <=50K                 ?       40.164760
1    <=50K          Cambodia       41.416667
2    <=50K            Canada       37.914634
3    <=50K             China       37.381818
4    <=50K          Columbia       38.684211
..     ...               ...             ...
77    >50K          Thailand       58.333333
78    >50K   Trinadad&Tobago       40.000000
79    >50K     United-States       45.505369
80    >50K           Vietnam       39.200000
81    >50K        Yugoslavia       49.500000

[82 rows x 3 columns]

    salary native-country  hours-per-week
24   <=50K          Japan       41.000000
65    >50K          Japan       47.958333